//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ATE_TEST.rc
//
#define IDOK4                           2
#define IDC_BUTTON_SEARCH               2
#define IDC_BUTTON_SEARCHINFO           2
#define IDOK2                           3
#define IDOK5                           3
#define IDOK3                           4
#define IDOK6                           7
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ATE_TEST_DIALOG             102
#define IDD_SYSTEM                      103
#define IDD_WEB                         105
#define IDD_ADM_DATABASE                106
#define IDD_SAVE_ADM                    107
#define IDD_DIALOG_INPUTFILENAME        109
#define IDR_MAINFRAME                   128
#define IDR_MYMENU                      129
#define IDR_TOOLBAR1                    130
#define IDR_ICON1                       132
#define IDI_ICON1                       135
#define IDI_ICON2                       136
#define IDD_SET_USER                    137
#define IDD_LOGIN                       140
#define IDI_ICON3                       154
#define IDI_ICON4                       155
#define IDD_SET_RESOURCE                157
#define IDI_ICON7                       160
#define IDI_ICON8                       161
#define IDI_ICON5                       163
#define IDI_ICON6                       164
#define IDR_MENU_SOURCE                 166
#define IDD_DIALOG_INSSET               167
#define IDD_AUTOTEST                    169
#define IDD_INSDOC                      170
#define IDD_MODIFYADVISE                171
#define IDI_ICON9                       172
#define IDB_BITMAP2                     173
#define IDB_BITMAP3                     174
#define IDB_BITMAP4                     176
#define IDB_BITMAP5                     177
#define IDD_DIALOG_TESTSET              178
#define IDB_BITMAP6                     183
#define IDB_BITMAP_TEST                 183
#define IDB_BITMAP7                     184
#define IDB_BITMAP8                     185
#define IDB_BITMAP9                     186
#define IDB_BITMAP10                    190
#define IDB_BITMAP11                    191
#define IDB_BITMAP12                    192
#define IDB_BITMAP13                    193
#define IDB_BITMAP14                    194
#define IDB_BITMAP15                    195
#define IDB_BITMAP16                    196
#define IDD_DIALOG_TESTEND              198
#define IDB_BITMAP17                    199
#define IDB_BITMAP_TEST1                209
#define IDB_BITMAP_MODEL                210
#define IDB_BITMAP_MODEL1               211
#define IDB_BITMAP_REPORT               212
#define IDB_BITMAP_REPORT1              213
#define IDB_BITMAP_SYSTEM               214
#define IDB_BITMAP_SYSTEM1              215
#define IDB_BITMAP_REMOTE               216
#define IDB_BITMAP_REMOTE1              217
#define IDB_BITMAP_MONITER              218
#define IDB_BITMAP_MONITER1             219
#define IDB_BITMAP_HELP                 220
#define IDB_BITMAP_HELP1                221
#define IDD_DIALOG_TESTCONFIG           226
#define IDD_DIALOG_TESTTEMPLE           227
#define IDB_BITMAP_SUBFORM              228
#define IDD_DIALOG_REPORT               230
#define IDD_DIALOG_CONNECT              231
#define IDD_TEM_FIRST                   233
#define IDD_TEM_CONTENT                 234
#define IDD_DIALOG_FAIL                 237
#define IDD_DIALOG_UUTBASICINFO         238
#define IDD_DIALOG_SETINSTR             240
#define IDR_CONTEXTMENU                 241
#define IDD_INSDOC_BASIC                242
#define IDD_INSDOC_TEMPLETE             243
#define IDD_INSDOC_SOLUTION             244
#define IDB_PIC_BASIC1                  245
#define IDB_PIC_TEMPLETE                246
#define IDB_PIC_BASIC                   247
#define IDB_PIC_TEMPLETE1               248
#define IDB_PIC_SOLUTION                249
#define IDB_PIC_SOLUTION1               250
#define IDB_BITMAP_INSSET               251
#define IDD_DIALOG_ADD_KIND             252
#define IDD_INSDOC_TEMPLETE_CHANGE      253
#define IDR_MENU_TEST_TEMPLETE          254
#define IDD_DIALOG_MODEL_LIST           255
#define IDD_DIALOG_ADD_MODEL            256
#define IDR_MENU_INS_BASIC              257
#define IDD_DIALOG_TEMPLATE_LIST        257
#define IDD_DIALOG_TEMPLATE_DEL         258
#define IDD_DIALOG_TEMPLATE_TEST_CONDITION 259
#define IDR_MENU_TEMPLATE_SOLUTION      259
#define IDC_EDIT_INSBASIC_LIST_CUSTOM   260
#define IDD_DIALOG_SOLUTION_DEL         260
#define IDR_MENU_SOLUTION               260
#define IDC_COMBO_INSBASIC_LIST_CUSTOM  261
#define IDD_DIALOG_SOLUTION_LIST        261
#define IDC_EDIT_INSTEMPLATE_LIST_CUSTOM 262
#define IDD_DIALOG_EDT_LUA_PIC          262
#define IDC_COMBO_INSTEMPLATE_LIST_CUSTOM 263
#define IDD_DIALOG_LUA_LIST             263
#define IDC_COMBO_INSTEMPLATE_LIST_CUSTOM1 264
#define IDD_DIALOG_PIC_LIST             264
#define IDC_EDIT_INSTEMP_CONDITION      265
#define IDD_DIALOG_REGIST               265
#define IDB_BITMAP_REG_TITLE            268
#define IDD_INSDOC_TEMPLATE_EXCEL       269
#define IDD_DIALOG_TEST_LUA             271
#define IDR_MENU_LUA                    272
#define IDC_CURSOR1                     276
#define IDR_MENU_CODE_TEXT              277
#define IDI_ICON10                      279
#define IDI_ICON11                      281
#define IDD_DIALOG_TEST_LUA_ADD_FUN     282
#define IDB_PIC_SOLUTION_DEVICE         283
#define IDB_PIC_SOLUTION_DEVICE1        284
#define IDB_PIC_SOLUTION_LUA            285
#define IDB_PIC_SOLUTION_LUA1           286
#define IDI_ICON12                      287
#define IDI_ICON13                      288
#define IDD_DIALOG_FRONT_PAGE           289
#define IDD_DIALOG_FILL_ROW             290
#define IDB_BITMAP18                    293
#define IDB_BITMAP1                     294
#define IDC_STATIC_FRAME                1001
#define IDC_NEW_BTN                     1002
#define IDC_DEL_BTN                     1003
#define IDC_CHANGE_BTN                  1004
#define IDC_SAVE_BTN                    1005
#define IDC_RET_BTN                     1006
#define IDC_STATIC_NAME                 1007
#define IDC_EDIT_NAME                   1008
#define IDC_STATIC_PWD1                 1009
#define IDC_EDIT_PWD                    1010
#define IDC_STATIC_PWD2                 1011
#define IDC_EDIT_PWD2                   1012
#define IDC_COMBO_POW                   1013
#define IDC_LIST_USER                   1014
#define IDC_EDIT_PSW                    1017
#define IDC_STATIC_PSW                  1019
#define IDC_TREE_RES                    1020
#define IDC_EDIT_USERNAME               1021
#define IDC_STATIC_USERNAME             1022
#define IDC_EDIT1                       1026
#define IDC_EDIT_INSNAME                1026
#define IDC_EDIT_NUMBER                 1026
#define IDC_EDIT_DOC                    1026
#define IDC_LIST1                       1027
#define IDC_LIST_BASIC                  1027
#define IDC_EDIT_INSMODEL               1027
#define IDC_LIST_RESULT                 1027
#define IDC_LIST_Reason                 1027
#define IDC_LIST_POINT                  1027
#define IDC_LIST_ADVISE                 1027
#define IDC_EDIT6                       1027
#define IDC_LIST_RESULT_INSDOC          1027
#define IDC_LIST_TEST_ITEM              1027
#define IDC_STATIC_SOURCE               1028
#define IDC_EDIT_CHANNEL                1028
#define IDC_EDIT_UPPER                  1028
#define IDC_LIST_ADVISE2                1028
#define IDC_EDIT_NUMBER2                1028
#define IDC_EDIT_CUSTOMER               1028
#define IDC_EDIT_INSFACTORY             1028
#define IDC_EDIT2                       1028
#define IDC_LIST4                       1028
#define IDC_EDIT7                       1028
#define IDC_LIST_TESTRESULT             1028
#define IDC_EDIT_DESCRIP_CONN           1028
#define IDC_EDIT_MODEL_INSDOC           1028
#define IDC_LIST_LUA                    1028
#define IDC_EDIT_FUN_LUA                1028
#define IDC_STATIC_INS                  1029
#define IDC_EDIT_MANU                   1029
#define IDC_EDIT_MODEL                  1029
#define IDC_EDIT_LOWER                  1029
#define IDC_EDIT3                       1029
#define IDC_EDIT_INSFACTORY2            1029
#define IDC_EDIT_MANUFACTORY_INSDOC     1029
#define IDC_LIST_INFO                   1030
#define IDC_EDIT_ADDRESS                1030
#define IDC_EDIT_MANUFACTORY            1030
#define IDC_EDIT_UNIT                   1030
#define IDC_EDIT4                       1030
#define IDC_EDIT_CONCLUSION             1030
#define IDC_EDIT_INSNAME2               1030
#define IDC_EDIT_TEMP                   1030
#define IDC_EDIT_UUT                    1030
#define IDC_EDIT_SNumber                1031
#define IDC_EDIT_STATION                1031
#define IDC_EDIT_NUMBER3                1031
#define IDC_EDIT5                       1031
#define IDC_EDIT_NUMBER_M               1031
#define IDC_EDIT_INSNAME3               1031
#define IDC_EDIT_NUMBER4                1032
#define IDC_EDIT_TEMPER                 1032
#define IDC_EDIT_INSNAME4               1032
#define IDC_EDIT_NUMBER5                1033
#define IDC_EDIT_SHI                    1033
#define IDC_STATIC_INFO                 1034
#define IDC_EDIT_CUSTADD                1034
#define IDC_COMBO_INSKIND               1035
#define IDC_EDIT_CUSTOMER2              1035
#define IDC_EDIT_IP                     1035
#define IDC_COMBO_INSDRIVER             1036
#define IDC_STATIC_INSNAME              1037
#define IDC_TREE_TPS                    1040
#define IDC_LIST_STATUS                 1041
#define IDC_LIST_INS                    1042
#define IDC_PIC_CONN                    1044
#define IDC_STATIC_BASICINFO            1045
#define IDC_BUTTON1                     1046
#define IDC_BUTTON_TEST                 1046
#define IDC_AUTOTEST                    1046
#define IDC_BUTTON_OPEN                 1046
#define IDC_BUTTON_ADD                  1046
#define IDC_BUTTON_OK                   1046
#define IDC_BUTTON_TPSAVE               1046
#define IDC_BUTTON2                     1047
#define IDC_BUTTON_STOP                 1047
#define IDC_MANUTEST                    1047
#define IDC_BUTTON_MODIFY               1047
#define IDC_BUTTON_MODU                 1047
#define IDC_BUTTON3                     1048
#define IDC_BUTTON_PAUSE                1048
#define IDC_SYSTEMSET                   1048
#define IDC_UUTDOC                      1048
#define IDC_BUTTON_DELETE               1048
#define IDC_BUTTON_TESTCONFIG           1048
#define IDC_TESTPROCESS                 1049
#define IDC_EXIT                        1049
#define IDC_BUTTON_SERACH               1049
#define IDC_BUTTON_SAVE                 1049
#define IDC_STATIC_BASICINFO2           1049
#define IDC_BUTTON_ITEMADD              1049
#define IDC_BUTTON4                     1049
#define IDC_STATIC_PROCESS              1050
#define IDC_ASSISTANT                   1050
#define IDC_BUTTON_RETURN               1050
#define IDC_BUTTON_TPCONFIG             1050
#define IDC_BUTTON_STOP2                1050
#define IDC_BUTTON5                     1050
#define IDC_BUTTON_REPORT               1050
#define IDC_BUTTON_TESTSET              1051
#define IDC_BUTTON_ITEMMODIFY           1051
#define IDC_BUTTON6                     1051
#define IDC_BUTTON_ITEMDEL              1052
#define IDC_BUTTON7                     1052
#define IDC_BUTTON_STOP3                1052
#define IDC_BUTTON_TPSAVE2              1053
#define IDC_BUTTON_STOP4                1053
#define IDC_RICHEDIT1                   1054
#define IDC_BUTTON_TPCONFIG2            1054
#define IDC_BUTTON_STOP5                1054
#define IDC_LIST_DOC                    1055
#define IDC_BUTTON_RESULTSAVE           1055
#define IDC_BUTTON_INSTRSTATE           1056
#define IDC_STATIC_MODEL                1059
#define IDC_STATIC_MANUFACT             1060
#define IDC_STATIC_LIST                 1061
#define IDC_STATIC5                     1062
#define IDC_STATIC_NUM                  1063
#define IDC_EDIT_SEARCH                 1064
#define IDC_STATIC_TEMPLETE             1064
#define IDC_STATIC_NUM2                 1065
#define IDC_STATIC_NUM3                 1066
#define IDC_STATIC_NUM4                 1067
#define IDC_STATIC_NUM5                 1068
#define IDC_COMBO_REMOTEPORT            1069
#define IDC_STATIC_NUM6                 1069
#define IDC_COMBO_TESTMODE              1070
#define IDC_STATIC_NUM7                 1070
#define IDC_EDIT_ATTEN                  1071
#define IDC_STATIC_NUM8                 1071
#define IDC_EDIT_FREQ                   1072
#define IDC_STATIC6                     1072
#define IDC_BUTTON_SETM                 1073
#define IDC_STATIC_NUM9                 1073
#define IDC_STATIC_NUM10                1074
#define IDC_CHECK1                      1075
#define IDC_STATIC_NUM11                1075
#define IDC_CHECK_SAVE                  1075
#define IDC_CHECK2                      1076
#define IDC_SPIN1                       1076
#define IDC_CHECK_REPORT                1076
#define IDC_STATIC_SOLUSION             1076
#define IDC_COMBO1                      1077
#define IDC_COMBO_MODULE                1077
#define IDC_COMBO_DRIVER                1077
#define IDC_COMBO_RESULT                1077
#define IDC_COMBO2                      1078
#define IDC_COMBO_DUETIME               1078
#define IDC_COMBO_TPNAME                1078
#define IDC_COMBO_DRIVER_NAME           1078
#define IDC_COMBO_TEST_LUA_SERI         1078
#define IDC_MONTHCALENDAR1              1079
#define IDC_COMBO_DEFTMODU              1079
#define IDC_COMBO_TESTSTATION           1079
#define IDC_COMBO_DRIVER_NAME2          1079
#define IDC_DATETIMEPICKER1             1080
#define IDC_DATETIME_CAL                1080
#define IDC_COMBO_DEFTCONFIG            1080
#define IDC_DATETIME_START              1080
#define IDC_PROGRESS1                   1081
#define IDC_COMBO_DEFTCONFIG2           1081
#define IDC_PROGRESS_TEST               1081
#define IDC_DATETIMEPICKER2             1081
#define IDC_DATETIME_STOP               1081
#define IDC_COMBO_INSUSE                1082
#define IDC_STATIC_INSINFO              1083
#define IDC_COMBO_SOLUTION              1083
#define IDC_STATIC_ITEMINFO             1084
#define IDC_EDIT_ITEMNAME               1086
#define IDC_STATIC_LINE                 1087
#define IDC_EDIT_TESTSET                1087
#define IDC_LIST2                       1088
#define IDC_LIST3                       1089
#define IDC_TREE_CONFIG                 1090
#define IDC_EDIT_INSADDRESS             1091
#define IDC_EDIT_INSCHANNEL             1092
#define IDC_LIST_FUNCTION               1093
#define IDC_LIST_INSREQUIRED            1094
#define IDC_STATIC_ITEMSET              1095
#define IDC_BORDER_RIGHT                1097
#define IDC_STATIC_DRIVENAME            1099
#define IDC_STATIC_INSADDRESS           1100
#define IDC_STATIC_INSCHANNEL           1101
#define IDC_STATIC_FUNC                 1102
#define IDC_LIST5                       1104
#define IDC_TAB1                        1105
#define IDC_STATIC_PROGRESS             1106
#define IDC_DATABASE_SEL                1107
#define IDC_CHECK_ALL                   1108
#define IDC_SEL_SAVE_PATH               1108
#define IDC_SAVE_PATH                   1109
#define IDC_TREE_TEMP                   1109
#define IDC_CALIBRATION_ALL             1109
#define IDC_STATIC_CONCLUSION           1110
#define IDC_IP_PATH                     1110
#define IDC_PORT                        1111
#define IDC_STATIC_PIC                  1112
#define IDC_SET_WEB                     1112
#define IDC_STATIC_PATH                 1113
#define IDC_TAB_TEM                     1113
#define IDC_STATIC_PORT                 1114
#define IDC_LIST_FIRST                  1114
#define IDC_BUTTON_PAPER                1115
#define IDC_STATIC2                     1116
#define IDC_BUTTON_PAPER2               1116
#define IDC_RETURN                      1116
#define IDC_STATIC1                     1117
#define IDC_COMBO_SEARCH                1117
#define IDC_EDIT_CONTENT                1118
#define IDC_LIST_TESTINFO               1119
#define IDC_STATIC_USER                 1121
#define IDC_EDIT_MAINSTATUS             1123
#define IDC_EDIT_LIST                   1124
#define IDC_STATIC_PICRECT              1125
#define IDC_STATIC_TESTTIME             1126
#define IDC_BUTTON_RETEST               1127
#define IDC_BUTTON_IGNOR                1128
#define IDC_EDIT_RESULT                 1129
#define IDC_STATIC_ELAPTIME             1130
#define IDC_BUTTON_IGNOR2               1130
#define IDC_STATIC_UNIT                 1131
#define ID_BUTTON_OK                    1132
#define IDC_BUTTON_GETSN                1133
#define IDC_BUTTON_SAVEINTR             1134
#define IDC_LIST_INSTRINFO              1135
#define IDC_EDIT_INSTRADDRESS           1136
#define IDC_BUTTON_QUIT                 1137
#define IDC_STATIC_NAME_INSDOC          1137
#define IDC_STATIC_MODEL_INSDOC         1138
#define IDC_STATIC_FACTORY_INSDOC       1139
#define IDC_EDIT_NAME_INSDOC            1140
#define IDC_GROUP_BASIC_INSDOC          1141
#define IDC_STATIC_TEST_TTEM            1142
#define IDC_STATIC_TEST_ITEM            1142
#define IDC_BUTTON_SAVE_TEST_ITEM       1144
#define IDC_STATIC_TESTMODEL_INSDOC     1145
#define IDC_COMBO_MODULE_INSDOC         1146
#define IDC_COMBO_TEMPLETE_INSDOC       1146
#define IDC_BUTTON_ADD_TESTMODEL        1147
#define IDC_STATIC_SOLUTION_INSDOOC     1148
#define IDC_BUTTON_DEL_TESTMODEL        1148
#define IDC_COMBO_SOLUTION_INSDOC       1149
#define IDC_BUTTON_ADD_SOLUTION_IN_TEMPLATE 1149
#define IDC_BUTTON_ADD_TESTSOLUTION     1150
#define IDC_BUTTON_DEL_SOLUTION_IN_TEMPLATE 1150
#define IDC_LIST_RESULT1_INSDOC         1151
#define IDC_BUTTON_DEL_TESTSOLUTION     1151
#define IDC_LIST_INS_INSDOC             1152
#define IDC_STATIC_RELAY_TEMP           1153
#define IDC_STATIC_UNIT_UNDER_TEST      1154
#define IDC_LIST_UNIT_UNDER_TEST        1155
#define IDC_STATIC_INS_INSDOC           1157
#define IDC_PIC_BASIC                   1159
#define _REG_TITLE                      1159
#define IDC_PIC_TEMPLETE                1160
#define IDC_PIC_SOLUTION                1161
#define IDC_GROUP_TEST_ITEM             1162
#define IDC_BUTTON_HAS_ENGINE           1164
#define IDC_BUTTON_HAS_NO_ENGINE        1165
#define IDC_LIST_SOLUTION_IN_TEMPLETE   1166
#define IDC_STATIC_SOLUTION_IN_TEMPLETE 1167
#define IDC_GROUP_UNIT_UNDER_TEST       1168
#define IDC_GROUP_INS_INSDOC            1169
#define IDC_EDIT_UUT_ADDRESS            1170
#define IDC_STATIC_UUT_ADDR             1171
#define IDC_STATIC_ADDRESS_INS          1172
#define IDC_EDIT_ADDRESS_INS            1173
#define IDC_COMBO_INS                   1174
#define IDC_STATIC_DRIVER_NAME_INS      1176
#define IDC_BUTTON_DRIVER_NAME          1177
#define IDC_BUTTON_SAVE_SOLUTION        1178
#define IDC_BUTTON_SAVE_UUT             1179
#define IDC_BUTTON_SAVE_INS             1180
#define IDC_STATIC_UUT_NAME             1181
#define IDC_STATIC_DRIVER_NAME_INS2     1181
#define IDC_EDIT_UUT_NAME               1182
#define IDC_LIST_MODEL                  1183
#define IDC_BUTTON_DRIVER_NAME2         1183
#define IDC_EDIT_MODEL_NAME             1184
#define IDC_EDIT_MODEL_FACTORY          1185
#define IDC_LIST_TEMPLATE               1187
#define IDC_EDIT_TEMPLATE_LIST          1188
#define IDC_STATIC_TEMPLATE_LIST        1189
#define IDC_LIST_TEMPLATE_DEL           1190
#define IDC_LIST_TEMPLATE_TEST_CONDITION 1191
#define IDC_BUTTON_SAVE_TEMPLATE        1192
#define IDC_BUTTON_SAVE_SOLUTION_IN_TEMPLATE 1193
#define IDC_BUTTON_SHOW_EXE             1195
#define IDC_BUTTON_EDT_LUA_PIC          1196
#define IDC_BUTTON_CHANGE_EXE           1196
#define IDC_EDIT_REQUEST                1197
#define IDC_EDIT_REGISTER               1198
#define IDC_PIC_REG_TITLE               1199
#define IDC_BUTTON_ADD_TEST_ITEM        1200
#define IDC_BUTTON_DEL_TEST_ITEM        1201
#define IDC_STATIC_SOLUTION_IN_TEMPLATE 1202
#define IDC_PIC_UUT                     1203
#define IDC_GROUP_TEMPLATE              1204
#define IDC_BUTTON_SOLUTION_CHANGE      1205
#define IDC_BUTTON_CHANGE_TEMPLATE      1206
#define IDC_GROUP_SOLUTION              1206
#define IDC_PIC_LUA                     1207
#define IDC_STATIC_LUA_PIC              1208
#define IDC_EDIT_EXPLAIN                1210
#define IDC_DSOFRAMER                   1211
#define IDC_STATIC_LUA_SYMBOL           1212
#define IDC_STATIC_LUA_TEXT             1213
#define IDC_SCROLLBAR_LUA_HSCROLL       1214
#define IDC_SCROLLBAR_LUA_VSCROLL       1216
#define IDC_TREE_LUA_FUNC               1217
#define IDC_LIST_VARIANT                1218
#define IDC_STATIC_OUTPUT               1219
#define IDC_STATIC_DEBUG                1220
#define IDC_STATIC_VATIANT              1221
#define IDC_EDIT_OUT_PUT                1222
#define IDC_STATIC_ENGINE_FUNC          1223
#define IDC_EDIT_LUA_FUNC_DISC          1224
#define IDC_STATIC_LUA_NAME             1226
#define IDC_COMBO_TEST_LUA_MODE         1227
#define IDC_BUTTON_TEST_LUA_INST_FUN    1228
#define IDC_EDIT_TEST_LUA_ADDR          1229
#define IDC_EDIT_TEST_LUA_PARA          1230
#define IDC_EDIT_FUN_C                  1231
#define IDC_LIST_TEST_LUA_ADD_FUN       1232
#define IDC_BUTTON_EXCEL_FRONT_PAGE     1233
#define IDC_EDIT_EXCEL_FRONT_PAGE       1234
#define IDC_LIST_EXCEL_FRONT_PAGE       1235
#define IDC_BUTTON_MOVEUP               1236
#define IDC_BUTTON_MOVEDOWN             1237
#define IDC_EDIT_FILL_ROW               1237
#define IDC_BUTTON_CONNECT_IGNORE_ITEM  1238
#define IDC_PIC_TEST_CONNECT            1239
#define IDC_Quit_BUTTON                 1240
#define IDC_IgnoreDialog_BUTTON         1241
#define IDC_CH_EDIT                     1242
#define IDC_VSG_EDIT2                   1243
#define IDC_CH_EDIT3                    1244
#define IDC_ROUT_EDIT3                  1244
#define ID_MENUITEM32772                32772
#define ID_MENUITEM32773                32773
#define ID_MENUITEM32774                32774
#define ID_MENUITEM32775                32775
#define ID_MENUITEM32776                32776
#define ID_MENU_PRINT                   32777
#define ID_MENU_SETUSER                 32778
#define ID_MENU_SETALL                  32779
#define ID_MENU_SETSOURCE               32780
#define ID_MENU_SETDOCUMENT             32781
#define ID_MENU_SELFTEST                32782
#define ID_MENU_CHANNELADJUST           32783
#define ID_MENU_INSTRUADJUST            32784
#define ID_MENUITEM32787                32785
#define ID_MENUITEM32788                32786
#define ID_MENUITEM32789                32787
#define ID_MENUITEM_AUTOTEST            32787
#define ID_MENU_SELFTESTINFO            32788
#define ID_MENUITEM32793                32789
#define ID_MENU_SEARCHREF               32790
#define ID_MENU_TEST                    32791
#define ID_MENU_MATERIAL                32792
#define ID_MENUITEM32811                32793
#define ID_MENUITEM32803                32794
#define ID_MENUITEM32802                32795
#define ID_MENU_BACK                    32796
#define ID_MENU_CREATE                  32816
#define ID_MENU_MODIFY                  32817
#define ID_MENU_DELETE                  32818
#define IDD_ADD_MODEL                   32819
#define IDD_ADD_KIND                    32820
#define IDD_LOOK_MODLE                  32821
#define IDD_CHANGE_MODEL                32822
#define IDD_DEL_MODEL                   32823
#define IDD_DEL_KIND                    32824
#define ID_MENU_TEMPLETE_ADD            32825
#define ID_MENU_INS_BASIC_ADD           32828
#define ID_MENU_INS_BASIC_DEL           32829
#define ID_MENU_INS_BASIC_NEW           32830
#define ID_MENU_TEMPLETE_DEL            32831
#define ID_MENU_TEMPLETE_COPY           32832
#define ID_MENU_TEMPLETE_SOLUTION_DEL   32834
#define ID_MENU_CLEAR_CELL              32835
#define IDR_TEMPLATE_SOLUTION_ADD       32836
#define IDR_START_DEBUG                 32837
#define IDR_LUA_DEBUG1                  32838
#define IDR_LUA_DEBUG2                  32839
#define IDR_STOP_DEBUG                  32840
#define IDR_LUA_DEL_ALL_BREAK           32841
#define IDR_LUA_SAVE                    32842
#define IDR_CODE_COPY                   32843
#define IDR_CODE_PASTE                  32844
#define IDR_CODE_CUT                    32845
#define IDR_CODE_DELETE                 32846
#define ID_MENU_TEMPLETE_FILL_ITEMROW   32848
#define ID_MENU_TEMPLETE_COPY_LINES     32850
#define ID_MENU_TEMPLETE_PAST           32851

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        295
#define _APS_NEXT_COMMAND_VALUE         32852
#define _APS_NEXT_CONTROL_VALUE         1243
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
